# This file overrides https://github.com/bbatsov/rubocop/blob/master/config/default.yml

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'

# Use UTF-8 as the source file encoding.
Encoding:
  Enabled: false

# Limit lines to 80 characters.
LineLength:
  Enabled: false

# Avoid methods longer than 10 lines of code
MethodLength:
  Enabled: false

# Favor modifier if/unless usage when you have a single-line body.
IfUnlessModifier:
  Enabled: false

# Favor modifier while/until usage when you have a single-line body.
WhileUntilModifier:
  Enabled: false

# Preferred collection methods.
CollectionMethods:
  Enabled: false

# Don't interpolate global, instance and class variables directly in strings.
VariableInterpolation:
  Enabled: false

# Use only ascii symbols in comments.
AsciiComments:
  Enabled: false

# Allow double quotes without string interpolation
StringLiterals:
  Enabled: false

# Allow comments like #this
LeadingCommentSpace:
  Enabled: false

# Disable checks for comment indentation
CommentIndentation:
  Enabled: false

# This cop checks that the ABC size of methods is not higher than the configured maximum. The ABC size is based on assignments, branches (method calls), and conditions.
Metrics/AbcSize:
  Enabled: false

# Allow use of self.method
RedundantSelf:
  Enabled: false

# Disable documentation checks
Documentation:
  Enabled: false
